### ISSUE TITLE
Check BWC License validity as early step

### ISSUE THREAD

**Issue by armab** [StackStorm/bwc-installer#28]
```
########################################################
       Installing BWC Enterprise unstable       
########################################################
########################################################
                 Using Unstable Repos
########################################################

    No access to enterprise repo 
    LICENSE: ... not valid.
  
```

I think it makes sense to verify BWC license validity before installing entire StackStorm Community version.
Installing StackStorm and all dependencies takes time and it might be annoying and counter-intuitive that after configuring almost everything script may hang with error, saying that license is not valid.

**Comment by LindsayHill** [comment]
That's a good point @armab - especially since we tell users "start again with a clean VM". If we detect the license failure early, they can fix that, and re-run the installer with the same system, since nothing has changed.

I'd also like to make some other changes - e.g. when running the BWC installation, if ST2 is already there, then just jump to the BWC section. This is related to some other changes I'd like to make to provide a form of idempotency to the install script. Not going to get full idempotency, but better handling of some common issues if someone attempts to re-run the script on a half-installed system. That's a separate discussion though
