### ISSUE TITLE
Install script should not bail out if ST2 already installed

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/bwc-installer#39]
If ST2 is already installed, then the installation script should go straight to the BWC installation step.

It should not attempt to re-install ST2 (and consequently fail).

This is because many users try to run the BWC install script on top of their ST2 installation, and are confused when it fails.

**Comment by armab** [comment]
@LindsayHill @warrenvw any ideas about approaches to take to solve this?

One of the approaches is to check by Enterprise installer if just `st2` package is in place. If yes, - skip the community and proceed to BWC installer step.

But the downside is: what if previous run of the community installer script wasn't finished 100% correctly and failed somewhere in the middle. Should we think about the corner cases like that or focus on minimal implementation first?
If we care about corner cases, - any opinions how to handle described situation better?

**Comment by warrenvw** [comment]
I'd be okay doing minimal implementation first, and then swinging back to work on corner cases as we build experience.

Current thoughts:

- How do we know when the installer is finished (either successfully or otherwise)? A simple check to see if the process is running is insufficient because the installer could have been interrupted. Should the installer touch a file with status? Or is there some other "bookend" that already exists for this purpose?
- IMHO, the bigger issue is how to identify if something failed somewhere in the middle. Processes with exit code other than 0 are easy to identify... it's the other failure scenarios that worry me. As an example, there's https://github.com/StackStorm/bwc-installer/issues/30. How can we be sure we've found all of those?

**Comment by LindsayHill** [comment]
Minimal implementation first (e.g. just check if ST2 package is installed) is probably a good start. That would resolve the most immediate problem, which is "people who have installed ST2, and want to upgrade BWC, so they run the BWC installer"). 

If someone did have a partial ST2 install, and we then ran the BWC installer on top, it would probably complete, but still with whatever gaps existed from ST2 failure (probably around either Mistral or ChatOps install). The group of people who have failed ST2 install, and want to run BWC installer on top of it, is a smaller group than those who have a working ST2 install, and just want to add BWC.

**Comment by warrenvw** [comment]
👍 Agreed.

**Comment by armab** [comment]
Thanks!
I've put everything together here https://github.com/StackStorm/bwc-installer/pull/47
